name: Issue
on:
  issues:
    types: [opened, edited, milestoned]
  issue_comment:
    types: [created, edited, deleted]
jobs:
  build:
    env:
      SRC: src/github.com/${{github.repository}}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
          JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
    - name: Fetch tags
      run: git fetch --prune --unshallow
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
    - name: Create release
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT" | jq '.event.issue.title'
        ACTOR=$(echo "$GITHUB_CONTEXT" | jq -r '.actor')
        [[ "$ACTOR" -eq drewwells ]] || { echo >&2 "actor does not have access to publish indexes"; exit 1; }
        VERSION=$(echo "$GITHUB_CONTEXT" | jq '.event.issue.title')
        TICKET=$(echo "$GITHUB_CONTEXT" | jq '.event.issue.number')
        echo Version: $VERSION
        # Sync submodule
        make APP_VERSION=${VERSION} SHELL='bash -x' sync
        # Build chart from this new tag and update index
        make TICKET=${TICKET} APP_VERSION=${VERSION} SHELL='bash -x' release update-index
